### PR TITLE
Build Docker image using Ploutos

### PR DESCRIPTION
**Pull request by ximon18**
This PR configures Ploutos to build an linux/amd64 and ARM cross-compiled Docker images and sanity checks the amd64 image by invoking the `krill-sync --version` command. It also adds support for using vendored TLS support to support compilation for cross-compiled targets in the same way we do for Krill.

The primary reason for adding this was to exercise/validate the `Dockerfile` as it was recently discovered not to be working with the version of Rust contained in the outdated Alpine base image it was using but this went unnoticed due to the build process not building the Docker image. This PR was then substantially updated to cover the https://github.com/NLnetLabs/krill-sync/pull/79 use case as well.

This PR will publish the produced image to Docker Hub per the rules [documented for Ploutos](https://github.com/NLnetLabs/ploutos/blob/main/docs/docker_packaging.md#outputs):

> If the required secrets are defined (see above), and the git ref is either the main branch or a v* tag, then the Docker image will be published to Docker Hub with the generated image name (see above).

An example successful run of the updated GitHub Action can be seen here: https://github.com/NLnetLabs/krill-sync/actions/runs/5936867130

### CODE REVIEW

**Review by timbru — APPROVED** [review]
Thanks!

So, if we want to publish the image on release, then that should be a separate triggered action no? We can do it, but I think it's not too urgent.

**Comment by ximon18** [comment]
No, Ploutous can handle that, but needs secrets adding to the repo.

**Review by timbru — APPROVED** [review]

**Comment by ximon18** [comment]
> Thanks!
> 
> So, if we want to publish the image on release, then that should be a separate triggered action no? We can do it, but I think it's not too urgent.

So, the PR has been updated to refer to Docker Hub credentials and those credentials have been created in Docker Hub and stored in GitHub as Variable `DOCKER_HUB_ID` and Secret `DOCKER_HUB_TOKEN`.

However, I had forgotten that Ploutos doesn't give you control over when it publishes to Docker Hub, rather it will publish images for builds on `main` or on release tags `vN` but not for any other branches or tags.

Is this okay @timbru?

**Comment by ximon18** [comment]
@timbru: Should the README be updated to say how to run with Docker?

**Pull request merged**
