### PR TITLE
Alternate Dockerfile approach that permits use of krill-sync CLI args

### PR DESCRIPTION
**Pull request by ximon18**
... as usual rather than using an ENV var based approach to configuring krill-sync inside the Docker container (as the current `Dockerfile` on `main` does). Also gets rid of the no longer needed `docker/entrypoint.sh` script.

### CODE REVIEW

**Comment by ximon18** [comment]
FYI @ties @StellaV, your feedback on this would be appreciated.

**Comment by ties** [comment]
Running an container with environment variables is something that I think is derived from the [12 factor apps](https://12factor.net/config) concept. It is an easy way to provide defaults for parameters and it decouples command line arguments from how you run the container.

Effectively it creates an external API for the application encapsulated by the container.

If you wish you can always override the command or the entrypoint later. That is why I see environment variables as a more idiomatic way to run docker containers.

I guess a lithmus test is whether the arguments from krill-sync 0.1 work with 0.2. If they do not, that is a clear example that this abstraction works.

**Comment by timbru** [comment]
@ties @ximon18 I lost track of this one completely. Is this still desired and relevant?

In future: please poke me if you are waiting for me ;)

**Comment by ximon18** [comment]
PR #77 removed the use of env vars as I standardized it on the way that the Krill and Routinator containers work. @ties: To your point about overcoming API changes, no it didn't help as the presence of the `--format` CLI argument in the `entrypoint.sh` script broke the invocation of `krill-sync` as it no longer supported it, though maybe your point was more that once `entrypoint.sh` was fixed one could still supply those env vars from outside and have them achieve the desired result. I dislike however having a separate API for Docker based usage compared to that of normal usage, and that that also becomes something we have to maintain and specify guarantees for. The expected way to use our app is via command line arguments, if it should support env vars the app itself should support them, not a wrapper script that we use with the Docker build process.

**Comment by ties** [comment]
> PR https://github.com/NLnetLabs/krill-sync/pull/77 removed the use of env vars as I standardized it on the way that the Krill and Routinator containers work. @ties: To your point about overcoming API changes, no it didn't help as the presence of the --format CLI argument in the entrypoint.sh script broke the invocation of krill-sync as it no longer supported it

True, there is a support cost there.

But keep in mind the difference between a wrapper and direct invocation here: Any direct usage of `--format` would break with this API change. A wrapper script could warn/ignore it when passed in.

I _dislike_ intelligent wrapper scripts but they have their use when migrating between arguments. Of course, ideally a container does not have a shell on the filesystem => there is no idiomatic way to have the wrapper script.

> I dislike however having a separate API for Docker based usage compared to that of normal usage, and that that also becomes something we have to maintain and specify guarantees for. The expected way to use our app is via command line arguments, if it should support env vars the app itself should support them, not a wrapper script that we use with the Docker build process.

I agree that the wrapper script is not a nice workaround. But when working with containers, using command line options is not idiomatic.

For example for routinetor, you would likely want the default to be `server`. However, you also want to inspect files _in_ the container from time to time. Using a "bare" `ENTRYPOINT` without an init replacement is annoying in this case. If you also want PID reaping, you may need an init replacement like tiny anyway.

Command line arguments do not mix the well with containers. Configuration files on volumes are annoying, but they work. Environment variables are the most idiomatic way (for me) to include required settings.

**Comment by ximon18** [comment]
Hi @ties,

> > PR #77 removed the use of env vars as I standardized it on the way that the Krill and Routinator containers work. @ties: To your point about overcoming API changes, no it didn't help as the presence of the --format CLI argument in the entrypoint.sh script broke the invocation of krill-sync as it no longer supported it
> 
> True, there is a support cost there.
> 
> But keep in mind the difference between a wrapper and direct invocation here: Any direct usage of `--format` would break with this API change. A wrapper script could warn/ignore it when passed in.

Yes, sorry, I thought my comment was clear that I acknowledged this case could have been handled by the wrapper.

> I _dislike_ intelligent wrapper scripts but they have their use when migrating between arguments. Of course, ideally a container does not have a shell on the filesystem => there is no idiomatic way to have the wrapper script.
> 
> > I dislike however having a separate API for Docker based usage compared to that of normal usage, and that that also becomes something we have to maintain and specify guarantees for. The expected way to use our app is via command line arguments, if it should support env vars the app itself should support them, not a wrapper script that we use with the Docker build process.
> 
> I agree that the wrapper script is not a nice workaround. But when working with containers, using command line options is not idiomatic.

In what way is it not idiomatic? The `docker run` command supports passing command line arguments to the container on startup, and passing environment variables also has to be done using the `--env` command line argument to the `docker run` command so is no better than command line arguments. Perhaps you are referring to the ease with which one can define environment variables in tooling that wraps around Docker, such as `docker-compose` or Kubernetes?

Let's look at the Docker Hub top 10 (actually 11, see the comment below the table) suggested [official Linux Docker images](https://hub.docker.com/search?q=&image_filter=official&operating_system=linux&type=image) that are not operating systems but applications:

| image | supports env var based config? | notes |
| --- | --- | --- |
| `nginx` | &check; | Only since 1.19, involves an "intelligent wrapper script" (they describe it as "a function, which will extract environment variables before nginx starts") |
| `redis` | &cross; | |
| `postgres` | &check; | |
| `httpd` | &cross; | |
| `mongo` | &check; | |
| `memcached` | &cross; | |
| `mysql` | &check; | |
| `traefik` | &cross; | |
| `rabbitmq` | &cross; | No longer supports env var based config since RabbitMQ 3.9 |
| `registry`| &cross; | |
| `wordpress`| &check; | |

_(I excluded `mariadb` as it is a fork of `mysql`, and added `wordpress` as I'm not sure that`registry` was a fair example, being from Docker and at a glance having seemingly no config at all)_

So, I'm not sure that it's fair to say that env var based configuration is idiomatic or needed, but indeed is supported by almost half of the top 10 suggested images.

> For example for routinetor, you would likely want the default to be `server`. However, you also want to inspect files _in_ the container from time to time. Using a "bare" `ENTRYPOINT` without an init replacement is annoying in this case. If you also want PID reaping, you may need an init replacement like tiny anyway.

If you want to inspect the files in the container from time to time you should exec into the container. If you wanted to look at the files in a fresh instance of the image you don't need an INIT process to reap orphaned child processes so tini isn't needed then anyway, and if in control of running the container yourself you may be able to get tini without the image support for it by using the Docker official support through the `--init` argument to `docker run`.

> Command line arguments do not mix the well with containers. Configuration files on volumes are annoying, but they work. Environment variables are the most idiomatic way (for me) to include required settings.

With the "(for me)" caveat we agree ;-)

The biggest issue for me here is that we had some sort of support for env var based configuration of the `krill-sync` Docker image (though that image wasn't building nor was the passing of settings to the application working once image building was fixed) and now with PR #77 that is no longer the case.

However, if we were to do environment variable based configuration of one image I think we should do it for our other images too, and we don't support them for the `routinator` image and have only limited support for configuring the `krill` image via env vars. It's unclear to me that this is really a priority and my time is unfortunately needed on other tasks so while I put the effort in to PR #77 I'd rather not invest more time at this point with changes to support env var based configuration. A PR to support it would be acceptable (to me at least, as I do see there is an argument for it), I'm just not sure I can get to this myself at the moment.

**Comment by ties** [comment]
> Let's look at the Docker Hub top 10 (actually 11, see the comment below the table) suggested [official Linux Docker images](https://hub.docker.com/search?q=&image_filter=official&operating_system=linux&type=image) that are not operating systems but applications:
> 
> image	supports env var based config?	notes
> `nginx`	✓	Only since 1.19, involves an "intelligent wrapper script" (they describe it as "a function, which will extract environment variables before nginx starts")
> `redis`	✗	
> `postgres`	✓	
> `httpd`	✗	
> `mongo`	✓	
> `memcached`	✗	
> `mysql`	✓	
> `traefik`	✗	
> `rabbitmq`	✗	No longer supports env var based config since RabbitMQ 3.9
> `registry`	✗	
> `wordpress`	✓	
> _(I excluded `mariadb` as it is a fork of `mysql`, and added `wordpress` as I'm not sure that`registry` was a fair example, being from Docker and at a glance having seemingly no config at all)_
> 
> So, I'm not sure that it's fair to say that env var based configuration is idiomatic or needed, but indeed is supported by almost half of the top 10 suggested images. I find it interesting that RabbitMQ **stopped** supporting env var based configuration.

Thanks for this deep dive!
What I see happening is that:
  * for superficial configuration, environment variables are often used
  * very complicated configuration often uses files
  * many systems have a hierarchy (e.g. `default > config > environment variable > arguments`) in which they resolve settings.

This hierarchy is powerful: I can apply the same configuration file (or default configuration) in two environments while overriding a single setting (e.g. a URL). The alternative of applying the same change in multiple configuration files is quite fragile in practice :).

Command line arguments are very powerful but also fragile (parsing failures are rejected). Unknown environment variables (or typo's) are ignored.

> The biggest issue for me here is that we had some sort of support for env var based configuration of the `krill-sync` Docker image (though that image wasn't building nor was the passing of settings to the application working once image building was fixed) and now with PR #77 that is no longer the case.
> 
> However, if we were to do environment variable based configuration of one image I think we should do it for our other images too, and we don't support them for the `routinator` image and have only limited support for configuring the `krill` image via env vars. It's unclear to me that this is really a priority and my time is unfortunately needed on other tasks so while I put the effort in to PR #77 I'd rather not invest more time at this point with changes to support env var based configuration. A PR to support it would be acceptable (to me at least, as I do see there is an argument for it), I'm just not sure I can get to this myself at the moment.

I agree with the cost/benefit analysis and not prioritising this type of configuration. If I end up re-creating environment based configuration I will make sure there is a PR. Furthermore, adding custom code for this in a dockerfile does not seem the best use of time, adding it to the main executable feels like a better way to go.

**Comment by timbru** [comment]
I am closing this PR for now as it seems to be obsoleted by events. Feel free to re-open if needed.

**Pull request closed without merging**
