### PR TITLE
Ensure that a different volume can be used

### PR DESCRIPTION
**Pull request by StellaV**
Updated hardcoded volume to using an environment variable

### CODE REVIEW

**Comment by ximon18** [comment]
Hi @StellaV,

Thanks for the contribution!

I'm not clear what problem you are trying to solve here. I see that you corrected what appears to be a missing `/` in `datarsync`, and using `$DATA` instead of hard-coded values is more consistent with the `entrypoint.sh` script use of a `$DATA` variable, but I'm not sure what problem is resolved by making the data directory path configurable in the first place. The data directory will be written to by krill-sync wherever krill-sync is told to write it, it doesn't matter to krill-sync where it is mounted inside the container and the location of mount point inside the container won't make any difference to the content of the Docker volume (as the relative paths inside the volume will remain the same).

I'm also not sure why one would want to add `/data` and `./data` to `.dockerignore`. Those directories are not part of the krill-sync Git repo and if you are using a Docker volume those directories will not exist on the host at all, instead they will only exist in the Docker volume.

I assume I am missing something here :-)

Separately, note that this Dockerfile was contributed by @ties but I have not yet had time to fully review it and to decide  whether or not we will use it in this form or not. In particular I am hoping to find time to look at this more closely to decide whether or not the use of environment variables instead of passing command line arguments from the host to directly to the invocation of krill-sync inside the container is really preferable. This is not consistent with how our other Docker images work and my instinct is to prefer passing command line arguments over using environment variables. As a user of the Docker image if you have any opinions about this I would be very interested in them. See the comments on #9 for more context.

Thanks,

Ximon

**Comment by StellaV** [comment]
Hi @ximon18 ,

Thanks for checking my PR so quickly!

Maybe a little bit of background of what Ties and I are trying to do here would be nice (we are in the same team, by the way). We want to sync the repositories using Docker and then let the data be used by other applications. This allows us to test any changes to or newer versions of krill-sync without influencing "production" data, simply by running one or more Docker containers.

The problem I'm trying to solve here (with the hardcoded /data) is that krill-sync creates a symlink in $DATA/rsync inside of the container. This will, of course, work within the container, but might not match what is on the filesystem. For example, if I mount /tmp/krill-sync to /data, I will end up with a broken symlink inside /tmp/krill-sync/rsync pointing to /data/rsync.... The last does not exist on the host filesystem.

To "fix" this, it would be better to just specify the volume directory to match the local path, instead. At least, this is the solution I managed to come up with (obviously, I am open to suggestions, improvements, etc.). The choice to use an ENV over an ARG was simply because the environment variable is also used within the entrypoint script. Plus some engineering curiosity whether one can use ENVs in the VOLUME definition. I personally don't see a reason to switch it, but maybe you have some good idea's on why one would be preferred over the other :)

The reason I added ./data to .dockerignore was simply to avoid someone accidentally pushing the directory to git, if they tested the container and added the volume in the repository path.

I hope this helps in your review of the PR? :) 

Kind regards,
Stella

**Comment by ximon18** [comment]
Hi @StellaV, apologies for the long delay in replying, we've been a bit busy with other things.

We're preparing to make a new release of krill-sync and so I'm looking back at this issue again now.

I can see the symlink problem with the 0.1.3 release code, but I can't reproduce it with the v0.2.0-dev code. With the new code the symlink is relative to the dir it is in and so works in both the container and on the host.

With krill-sync v0.1.3 you end up with something like this:

```
$ ll /tmp/ksrel/
total 20
drwxrwxr-x  4 krill_sync krill_sync 4096 jun 21 16:09 ./
drwxrwxrwt 30 root       root       4096 jun 21 16:21 ../
drwxr-xr-x  3 krill_sync krill_sync 4096 jun 21 16:09 rrdp/
lrwxrwxrwx  1 krill_sync krill_sync   24 jun 21 16:09 rsync -> /data/rsync.0_1624284559
drwxr-xr-x  4 krill_sync krill_sync 4096 jun 21 16:09 rsync.0_1624284559/
-rw-r--r--  1 krill_sync krill_sync  243 jun 21 16:09 state
```

With the latest 0.2.0 dev code you instead end up with this:

```
$  ll /tmp/ks020dev/rsync
total 12
drwxr-xr-x 3 krill_sync krill_sync 4096 jun 21 16:21 ./
drwxr-xr-x 4 krill_sync krill_sync 4096 jun 21 16:21 ../
lrwxrwxrwx 1 krill_sync krill_sync   54 jun 21 16:21 current -> session_c85a5e87-ad1a-4b5a-b73f-8325877826fd_serial_14/
drwxr-xr-x 4 krill_sync krill_sync 4096 jun 21 16:21 session_c85a5e87-ad1a-4b5a-b73f-8325877826fd_serial_14/
```

Note the lack of `data/` in the new sym link.

So I think this issue disappears with krill-sync v0.2.0-dev.

Ximon

**Comment by StellaV** [comment]
Hi @ximon18 , if it's indeed fixed in krill-sync v.02.0, then I will close this PR :)

Stella

**Pull request closed without merging**
