### PR TITLE
Docker container build with GitHub workflow

### PR DESCRIPTION
**Pull request by ties**
Adds a multi-architecture docker build using a GitHub workflow.

### CODE REVIEW

**Comment by ties** [comment]
Build seems to fail due to
```
 > [linux/arm64 build 5/5] RUN cargo build --target x86_64-alpine-linux-musl --release --locked:
47.25 error[E0463]: can't find crate for `compiler_builtins`
47.25 
49.07 error[E0432]: unresolved import `ffi::c_void`
49.07     --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.137/src/unix/mod.rs:1525:17
49.07      |
49.07 1525 |         pub use ::ffi::c_void;
49.07      |                 ^^^^^^^^^^^^^
49.07 
: could not compile `libc` (lib) due to 3 previous errors
52.03 warning: build failed, waiting for other jobs to finish...
```

**Comment by ties** [comment]
Should probably combine this with https://github.com/NLnetLabs/krill-sync/pull/77

**Comment by ximon18** [comment]
> Should probably combine this with #77

FYI I have updated #77 to include the cross-compilation case.

**Comment by timbru** [comment]
So, @ties I think we can close this PR and make sure it all works in #77, right?

**Comment by timbru** [comment]
closing this as it should be solved in #77

**Pull request closed without merging**
